# Generated by Django 4.1.1 on 2022-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.CharField(blank=True, max_length=128)),
                ("b", models.CharField(blank=True, max_length=128)),
                ("c", models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Bmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.CharField(blank=True, max_length=128)),
                ("b", models.CharField(blank=True, max_length=128)),
                ("d", models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
