# Generated by Django 4.1.1 on 2022-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="text", field=models.TextField(default=""),
        ),
    ]
